name: arabic-hate-speech
dependencies:
  - python=3.10
  - pip
  - pip:
    - transformers==4.41.0
    - datasets==2.19.0
    - torch==2.3.0
    - camel-tools
    - scikit-learn
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - optuna
    - tqdm
    - twarc
